### ISSUE TITLE
Convolution issue with Dimensions in states/embedded_states

### ISSUE THREAD

**Issue by StarBaseOne** [ku2482/fqf-iqn-qrdqn.pytorch#15]
Hi Toshiki

I'm having problems with running your code. It seems to me like there is a problem with the CNN architecture for base DQN. 

For all three algorithms, FQF, IQN, QRDQN, the experiments fail at different episode numbers. 
For instance running the  following:

`python train_qrdqn.py --cuda --env_id PongNoFrameskip-v4 --seed 0 --config config/qrdqn.yaml`

returns 
`RuntimeError: Expected 4-dimensional input for 4-dimensional weight [32, 15, 8, 8], but got 3-dimensional input of size [32, 15, 7] instead`

Other errors I've observed are.

- RuntimeError: Calculated padded input size per channel: (n x n). Kernel size: (8 x 8). Kernel size can't be greater than actual input size. 
- I also an error pertaining to  5-dimensional input of size [x,x,x,x,x] as opposed to 3-dimeniosnal input.

For instance at episode: 4788
```
Traceback (most recent call last):
  File "train_qrdqn.py", line 46, in <module>
    run(args)
  File "train_qrdqn.py", line 35, in run
    agent.run()
  File "/home/brian/ML/Distribute-Reinforcement-Learning/fqf_iqn_qrdqn/agent/base_agent.py", line 89, in run
    self.train_episode()
  File "/home/brian/ML/Distribute-Reinforcement-Learning/fqf_iqn_qrdqn/agent/base_agent.py", line 176, in train_episode
    self.train_step_interval()
  File "/home/brian/ML/Distribute-Reinforcement-Learning/fqf_iqn_qrdqn/agent/base_agent.py", line 197, in train_step_interval
    self.learn()
  File "/home/brian/ML/Distribute-Reinforcement-Learning/fqf_iqn_qrdqn/agent/qrdqn_agent.py", line 71, in learn
    quantile_loss, mean_q, errors = self.calculate_loss(
  File "/home/brian/ML/Distribute-Reinforcement-Learning/fqf_iqn_qrdqn/agent/qrdqn_agent.py", line 94, in calculate_loss
    self.online_net(states=states),
  File "/home/brian/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/brian/ML/Distribute-Reinforcement-Learning/fqf_iqn_qrdqn/model/qrdqn.py", line 48, in forward
    state_embeddings = self.dqn_net(states)
  File "/home/brian/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/brian/ML/Distribute-Reinforcement-Learning/fqf_iqn_qrdqn/network.py", line 48, in forward
    state_embedding = self.net(states)
  File "/home/brian/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/brian/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/brian/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/brian/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home/brian/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [32, 15, 8, 8], but got 3-dimensional input of size [32, 15, 7] instead
```
I've tried to use unsqueeze and squeeze methods in pytorch to change dimensions and get around this but I think perhaps the CNN network is causing this. Have you come across this before? 

PS: torch version is 1.7.1

Thanks
Brian

**Comment by toshikwa** [comment]
@hougiebear 
Sorry for the late response.

I haven't experienced it before, and I couldn't reproduce it.
Could you share the exact versions of torch, numpy, gym, CUDA, cuDNN ?
